export const STUDENT_LOGIN = 'STUDENT_LOGIN';
export const STUDENT_LOGIN_FULFILLED = 'STUDENT_LOGIN_FULFILLED';
export const STUDENT_LOGGEDIN = 'STUDENT_LOGGEDIN';
export const ADMIN_LOGGEDIN = 'ADMIN_LOGGEDIN';
export const ADMIN_LOGIN = 'ADMIN_LOGIN';
export const ADMIN_LOGIN_FULFILLED = 'ADMIN_LOGIN_FULFILLED';
