export const STUDENT_LOGIN = 'STUDENT_LOGIN';
export const STUDENT_LOGIN_FULFILLED = 'STUDENT_LOGIN_FULFILLED';
export const ADMIN_LOGGEDIN = 'ADMIN_LOGGEDIN';
export const ADMIN_LOGIN = 'ADMIN_LOGIN';
export const ADMIN_LOGIN_FULFILLED = 'ADMIN_LOGIN_FULFILLED';
export const POINTS_COHORT = 'POINTS_COHORT';
export const POINTS_COHORT_FULFILLED = 'POINTS_COHORT_FULFILLED';
export const SUBMISSIONS = 'SUBMISSIONS';
export const SUBMISSIONS_FULFILLED = 'SUBMISSIONS_FULFILLED';
<<<<<<< HEAD
export const CHALLNGES_CAMPUS = 'CHALLNGES_CAMPUS';
export const CHALLNGES_CAMPUS_FULFILLED = 'CHALLNGES_CAMPUS_FULFILLED';
=======
export const REQUESTS = 'REQUESTS';
export const REQUESTS_FULFILLED = 'REQUESTS_FULFILLED';
>>>>>>> d778d23295c8c097d3cbd64d961387c70a5050a9
