process.env.NODE_ENV = 'test';

const app = require('../app');
const supertest = require('supertest');
const knex = require('../knex');

beforeEach((done) => {
  knex.migrate.latest()
  .then(() => knex.seed.run())
  .then(() => {
    done();
  })
  .catch((err) => {
    done(err);
  });
});

afterEach((done) => {
  knex.migrate.rollback()
  .then(() => done())
  .catch((err) => {
    done(err);
  });
});

after(() => {
  knex.destroy();
});

describe('GET /submissions/cohorts/:cohort_id', () => {
  it('Should return all challenge submissions from a given campus', (done) => {
    supertest(app)
      .get('/api/submissions/cohorts/1')
      .set('Accept', 'application/json')
      .set('Cookie', 'authToken=adminToken')
      .expect((response) => {
        for (let i = 0; i < response.body.length; i++) {
          delete response.body[i].created_at;
          delete response.body[i].updated_at;
        }
      })
      .expect(200,
      [
        {
          id: 1,
          student_id: 1,
          challenge_id: 4,
          cohort_id: 1,
          category_id: 1,
          submission_message: 'Built an app that allows users to add their jacket size. It also tracks fulfillment status us to whether student has received their gSwag.',
          evaluation_message: null,
          submission_status: 'Approved',
          submission_attachment_1: null,
          submission_attachment_2: null,
          submission_attachment_3: null,
          submission_image_link_1: null,
          submission_image_link_2: null,
          submission_image_link_3: null,
          category: {
            id: 1,
            category: 'Education',
          },
          challenge: {
            id: 4,
            name: 'Full-stack Side Project',
            point_value: 200,
            description: 'Develop a side project using curriculum technology.',
            requirements_1: 'Use HTML, CSS, JS, React, or Angular',
            requirements_2: 'Build a backend server using Node, Express, Postgres, and Knex.',
            requirements_3: 'Use an outside API or make your own.',
            requirements_4: 'Must be approved by an instructor.',
            requirements_5: 'Must provide link to Repo.',
          },
          student: {
            id: 1,
            username: 'algorythmist',
            name: 'Thomas Stang',
          },
        },
        {
          id: 2,
          student_id: 3,
          challenge_id: 4,
          cohort_id: 1,
          category_id: 1,
          submission_message: 'Built an app that allows users to add their jacket size. It also tracks fulfillment status us to whether student has received their gSwag.',
          evaluation_message: null,
          submission_status: 'Approved',
          submission_attachment_1: 'http://ghoodies.herokuapp.com',
          submission_attachment_2: 'https://github.com/danielmarcgardner/gHoodies',
          submission_attachment_3: null,
          submission_image_link_1: 'https://ucarecdn.com/d50ece0e-f5e1-47fd-a492-d8561fe02ebb/',
          submission_image_link_2: null,
          submission_image_link_3: null,
          category: {
            id: 1,
            category: 'Education',
          },
          challenge: {
            id: 4,
            name: 'Full-stack Side Project',
            point_value: 200,
            description: 'Develop a side project using curriculum technology.',
            requirements_1: 'Use HTML, CSS, JS, React, or Angular',
            requirements_2: 'Build a backend server using Node, Express, Postgres, and Knex.',
            requirements_3: 'Use an outside API or make your own.',
            requirements_4: 'Must be approved by an instructor.',
            requirements_5: 'Must provide link to Repo.',
          },
          student: {
            id: 3,
            username: 'dan_m_g',
            name: 'Daniel Gardner',
          },
        },
        {
          id: 3,
          student_id: 2,
          challenge_id: 1,
          cohort_id: 1,
          category_id: 2,
          submission_message: 'Held one hour of office hours on May 6th',
          evaluation_message: null,
          submission_status: 'Pending approval',
          submission_attachment_1: null,
          submission_attachment_2: null,
          submission_attachment_3: null,
          submission_image_link_1: null,
          submission_image_link_2: null,
          submission_image_link_3: null,
          category: {
            id: 2,
            category: 'Community',
          },
          challenge: {
            id: 1,
            name: 'Hold TA Hours',
            point_value: 15,
            description: 'Hold TA hours for a junior cohort for at least an hour.',
            requirements_1: 'Hold hours between 5pm and 6pm or during lab time.',
            requirements_2: null,
            requirements_3: null,
            requirements_4: null,
            requirements_5: null,
          },
          student: {
            id: 2,
            username: 'leveluppal',
            name: 'Sanjeet Uppal',
          },
        },
        {
          id: 4,
          student_id: 1,
          challenge_id: 3,
          cohort_id: 1,
          category_id: 1,
          submission_message: 'Built an api that sends JSON of all ingredients in season for each month',
          evaluation_message: null,
          submission_status: 'Approved',
          submission_attachment_1: null,
          submission_attachment_2: null,
          submission_attachment_3: null,
          submission_image_link_1: null,
          submission_image_link_2: null,
          submission_image_link_3: null,
          category: {
            id: 1,
            category: 'Education',
          },
          challenge: {
            id: 3,
            name: 'Back-end Side Project',
            point_value: 75,
            description: 'Develop a side project using curriculum technology.',
            requirements_1: 'Build a backend server using Node, Express, Postgres, and Knex.',
            requirements_2: 'Use an outside API or make your own.',
            requirements_3: 'Must be approved by an instructor.',
            requirements_4: 'Must provide link to Repo.',
            requirements_5: null,
          },
          student: {
            id: 1,
            username: 'algorythmist',
            name: 'Thomas Stang',
          },
        },
        {
          id: 5,
          student_id: 3,
          challenge_id: 3,
          cohort_id: 1,
          category_id: 1,
          submission_message: 'Built an api that sends JSON of cheese by name, firmness, and animal type',
          evaluation_message: null,
          submission_status: 'Approved',
          submission_attachment_1: 'http://cheeswhiz.herokuapp.com/api-docs/',
          submission_attachment_2: 'https://github.com/danielmarcgardner/cheeswhiz',
          submission_attachment_3: null,
          submission_image_link_1: 'https://ucarecdn.com/d50ece0e-f5e1-47fd-a492-d8561fe02ebb/',
          submission_image_link_2: null,
          submission_image_link_3: null,
          category: {
            id: 1,
            category: 'Education',
          },
          challenge: {
            id: 3,
            name: 'Back-end Side Project',
            point_value: 75,
            description: 'Develop a side project using curriculum technology.',
            requirements_1: 'Build a backend server using Node, Express, Postgres, and Knex.',
            requirements_2: 'Use an outside API or make your own.',
            requirements_3: 'Must be approved by an instructor.',
            requirements_4: 'Must provide link to Repo.',
            requirements_5: null,
          },
          student: {
            id: 3,
            username: 'dan_m_g',
            name: 'Daniel Gardner',
          },
        },
        {
          id: 6,
          student_id: 2,
          challenge_id: 3,
          cohort_id: 1,
          category_id: 1,
          submission_message: 'Built an api that sends JSON of individual student songs and songs that belong to a group',
          evaluation_message: null,
          submission_status: 'Approved',
          submission_attachment_1: null,
          submission_attachment_2: null,
          submission_attachment_3: null,
          submission_image_link_1: null,
          submission_image_link_2: null,
          submission_image_link_3: null,
          category: {
            id: 1,
            category: 'Education',
          },
          challenge: {
            id: 3,
            name: 'Back-end Side Project',
            point_value: 75,
            description: 'Develop a side project using curriculum technology.',
            requirements_1: 'Build a backend server using Node, Express, Postgres, and Knex.',
            requirements_2: 'Use an outside API or make your own.',
            requirements_3: 'Must be approved by an instructor.',
            requirements_4: 'Must provide link to Repo.',
            requirements_5: null,
          },
          student: {
            id: 2,
            username: 'leveluppal',
            name: 'Sanjeet Uppal',
          },
        },
        {
          id: 7,
          student_id: 2,
          challenge_id: 5,
          cohort_id: 1,
          category_id: 3,
          submission_message: 'Published an article on using raw SQL',
          evaluation_message: null,
          submission_status: 'Approved',
          submission_attachment_1: null,
          submission_attachment_2: null,
          submission_attachment_3: null,
          submission_image_link_1: null,
          submission_image_link_2: null,
          submission_image_link_3: null,
          category: {
            id: 3,
            category: 'Career',
          },
          challenge: {
            id: 5,
            name: 'Write your heart out',
            point_value: 50,
            description: 'Publish an original article with a minimum 750 word length. Must be an additional article to the minimum requirement.',
            requirements_1: 'Article published to Medium or LinkedIn.',
            requirements_2: null,
            requirements_3: null,
            requirements_4: null,
            requirements_5: null,
          },
          student: {
            id: 2,
            username: 'leveluppal',
            name: 'Sanjeet Uppal',
          },
        },
        {
          id: 8,
          student_id: 2,
          challenge_id: 2,
          cohort_id: 1,
          category_id: 1,
          submission_message: 'Built a front-end app using SF Open data API to show all movies with filming locations in SF',
          evaluation_message: null,
          submission_status: 'Approved',
          submission_attachment_1: null,
          submission_attachment_2: null,
          submission_attachment_3: null,
          submission_image_link_1: null,
          submission_image_link_2: null,
          submission_image_link_3: null,
          category: {
            id: 1,
            category: 'Education',
          },
          challenge: {
            id: 2,
            name: 'Front-end Side Project',
            point_value: 75,
            description: 'Develop a side project using curriculum technology.',
            requirements_1: 'Use HTML, CSS, JS, React, or Angular',
            requirements_2: 'Use an outside API.',
            requirements_3: 'Must be approved by an instructor.',
            requirements_4: 'Must provide link to Repo.',
            requirements_5: null,
          },
          student: {
            id: 2,
            username: 'leveluppal',
            name: 'Sanjeet Uppal',
          },
        },
        {
          id: 9,
          student_id: 1,
          challenge_id: 2,
          cohort_id: 1,
          category_id: 1,
          submission_message: 'Built a front-end app to show what cocktails require what ingredients to be made',
          evaluation_message: null,
          submission_status: 'Approved',
          submission_attachment_1: null,
          submission_attachment_2: null,
          submission_attachment_3: null,
          submission_image_link_1: null,
          submission_image_link_2: null,
          submission_image_link_3: null,
          category: {
            id: 1,
            category: 'Education',
          },
          challenge: {
            id: 2,
            name: 'Front-end Side Project',
            point_value: 75,
            description: 'Develop a side project using curriculum technology.',
            requirements_1: 'Use HTML, CSS, JS, React, or Angular',
            requirements_2: 'Use an outside API.',
            requirements_3: 'Must be approved by an instructor.',
            requirements_4: 'Must provide link to Repo.',
            requirements_5: null,
          },
          student: {
            id: 1,
            username: 'algorythmist',
            name: 'Thomas Stang',
          },
        },
        {
          id: 10,
          student_id: 3,
          challenge_id: 2,
          cohort_id: 1,
          category_id: 1,
          submission_message: 'Built a front-end app using SF Open data API and Google Maps API what days and locations food trucks appear in SF',
          evaluation_message: null,
          submission_status: 'Approved',
          submission_attachment_1: 'http://truckingaround.surge.sh/',
          submission_attachment_2: 'https://github.com/danielmarcgardner/Trucking-Around',
          submission_attachment_3: null,
          submission_image_link_1: 'https://ucarecdn.com/d50ece0e-f5e1-47fd-a492-d8561fe02ebb/',
          submission_image_link_2: null,
          submission_image_link_3: null,
          category: {
            id: 1,
            category: 'Education',
          },
          challenge: {
            id: 2,
            name: 'Front-end Side Project',
            point_value: 75,
            description: 'Develop a side project using curriculum technology.',
            requirements_1: 'Use HTML, CSS, JS, React, or Angular',
            requirements_2: 'Use an outside API.',
            requirements_3: 'Must be approved by an instructor.',
            requirements_4: 'Must provide link to Repo.',
            requirements_5: null,
          },
          student: {
            id: 3,
            username: 'dan_m_g',
            name: 'Daniel Gardner',
          },
        },
        {
          id: 11,
          student_id: 2,
          challenge_id: 5,
          cohort_id: 1,
          category_id: 3,
          submission_message: 'Published article  on how bootcamp prep courses truly prepare you for web development immersive courses',
          evaluation_message: null,
          submission_status: 'Approved',
          submission_attachment_1: null,
          submission_attachment_2: null,
          submission_attachment_3: null,
          submission_image_link_1: null,
          submission_image_link_2: null,
          submission_image_link_3: null,
          category: {
            id: 3,
            category: 'Career',
          },
          challenge: {
            id: 5,
            name: 'Write your heart out',
            point_value: 50,
            description: 'Publish an original article with a minimum 750 word length. Must be an additional article to the minimum requirement.',
            requirements_1: 'Article published to Medium or LinkedIn.',
            requirements_2: null,
            requirements_3: null,
            requirements_4: null,
            requirements_5: null,
          },
          student: {
            id: 2,
            username: 'leveluppal',
            name: 'Sanjeet Uppal',
          },
        },
        {
          id: 12,
          student_id: 1,
          challenge_id: 5,
          cohort_id: 1,
          category_id: 3,
          submission_message: 'Published article on CSS tips to create an elegant site',
          evaluation_message: null,
          submission_status: 'Approved',
          submission_attachment_1: null,
          submission_attachment_2: null,
          submission_attachment_3: null,
          submission_image_link_1: null,
          submission_image_link_2: null,
          submission_image_link_3: null,
          category: {
            id: 3,
            category: 'Career',
          },
          challenge: {
            id: 5,
            name: 'Write your heart out',
            point_value: 50,
            description: 'Publish an original article with a minimum 750 word length. Must be an additional article to the minimum requirement.',
            requirements_1: 'Article published to Medium or LinkedIn.',
            requirements_2: null,
            requirements_3: null,
            requirements_4: null,
            requirements_5: null,
          },
          student: {
            id: 1,
            username: 'algorythmist',
            name: 'Thomas Stang',
          },
        },
        {
          id: 13,
          student_id: 3,
          challenge_id: 5,
          cohort_id: 1,
          category_id: 3,
          submission_message: 'Published article on making a career change',
          evaluation_message: null,
          submission_status: 'Approved',
          submission_attachment_1: 'https://www.linkedin.com/pulse/how-overcome-fear-changing-careers-daniel-gardner',
          submission_attachment_2: null,
          submission_attachment_3: null,
          submission_image_link_1: null,
          submission_image_link_2: null,
          submission_image_link_3: null,
          category: {
            id: 3,
            category: 'Career',
          },
          challenge: {
            id: 5,
            name: 'Write your heart out',
            point_value: 50,
            description: 'Publish an original article with a minimum 750 word length. Must be an additional article to the minimum requirement.',
            requirements_1: 'Article published to Medium or LinkedIn.',
            requirements_2: null,
            requirements_3: null,
            requirements_4: null,
            requirements_5: null,
          },
          student: {
            id: 3,
            username: 'dan_m_g',
            name: 'Daniel Gardner',
          },
        },
        {
          id: 14,
          student_id: 2,
          challenge_id: 1,
          cohort_id: 1,
          category_id: 2,
          submission_message: 'TA during Javascript intro course  on Jan 25th',
          evaluation_message: null,
          submission_status: 'Denied',
          submission_attachment_1: null,
          submission_attachment_2: null,
          submission_attachment_3: null,
          submission_image_link_1: null,
          submission_image_link_2: null,
          submission_image_link_3: null,
          category: {
            id: 2,
            category: 'Community',
          },
          challenge: {
            id: 1,
            name: 'Hold TA Hours',
            point_value: 15,
            description: 'Hold TA hours for a junior cohort for at least an hour.',
            requirements_1: 'Hold hours between 5pm and 6pm or during lab time.',
            requirements_2: null,
            requirements_3: null,
            requirements_4: null,
            requirements_5: null,
          },
          student: {
            id: 2,
            username: 'leveluppal',
            name: 'Sanjeet Uppal',
          },
        },
        {
          id: 15,
          student_id: 1,
          challenge_id: 1,
          cohort_id: 1,
          category_id: 2,
          submission_message: 'TA during Javascript intro course  on Jan 25th',
          evaluation_message: null,
          submission_status: 'Denied',
          submission_attachment_1: null,
          submission_attachment_2: null,
          submission_attachment_3: null,
          submission_image_link_1: null,
          submission_image_link_2: null,
          submission_image_link_3: null,
          category: {
            id: 2,
            category: 'Community',
          },
          challenge: {
            id: 1,
            name: 'Hold TA Hours',
            point_value: 15,
            description: 'Hold TA hours for a junior cohort for at least an hour.',
            requirements_1: 'Hold hours between 5pm and 6pm or during lab time.',
            requirements_2: null,
            requirements_3: null,
            requirements_4: null,
            requirements_5: null,
          },
          student: {
            id: 1,
            username: 'algorythmist',
            name: 'Thomas Stang',
          },
        },
        {
          id: 16,
          student_id: 3,
          challenge_id: 1,
          cohort_id: 1,
          category_id: 2,
          submission_message: 'TA during Javascript intro course  on Jan 25th',
          evaluation_message: null,
          submission_status: 'Denied',
          submission_attachment_1: null,
          submission_attachment_2: null,
          submission_attachment_3: null,
          submission_image_link_1: null,
          submission_image_link_2: null,
          submission_image_link_3: null,
          category: {
            id: 2,
            category: 'Community',
          },
          challenge: {
            id: 1,
            name: 'Hold TA Hours',
            point_value: 15,
            description: 'Hold TA hours for a junior cohort for at least an hour.',
            requirements_1: 'Hold hours between 5pm and 6pm or during lab time.',
            requirements_2: null,
            requirements_3: null,
            requirements_4: null,
            requirements_5: null,
          },
          student: {
            id: 3,
            username: 'dan_m_g',
            name: 'Daniel Gardner',
          },
        },
        {
          id: 17,
          student_id: 3,
          challenge_id: 2,
          cohort_id: 1,
          category_id: 1,
          submission_message: 'Built a front-end app for supSeasonal api',
          evaluation_message: null,
          submission_status: 'Pending approval',
          submission_attachment_1: 'http://react-to-the-season.herokuapp.com/',
          submission_attachment_2: 'https://github.com/danielmarcgardner/supseasonal-react',
          submission_attachment_3: null,
          submission_image_link_1: 'https://ucarecdn.com/d50ece0e-f5e1-47fd-a492-d8561fe02ebb/',
          submission_image_link_2: null,
          submission_image_link_3: null,
          category: {
            id: 1,
            category: 'Education',
          },
          challenge: {
            id: 2,
            name: 'Front-end Side Project',
            point_value: 75,
            description: 'Develop a side project using curriculum technology.',
            requirements_1: 'Use HTML, CSS, JS, React, or Angular',
            requirements_2: 'Use an outside API.',
            requirements_3: 'Must be approved by an instructor.',
            requirements_4: 'Must provide link to Repo.',
            requirements_5: null,
          },
          student: {
            id: 3,
            username: 'dan_m_g',
            name: 'Daniel Gardner',
          },
        },
        {
          id: 18,
          student_id: 1,
          challenge_id: 2,
          cohort_id: 1,
          category_id: 1,
          submission_message: 'Built a front-end app for supSeasonal api',
          evaluation_message: null,
          submission_status: 'Pending approval',
          submission_attachment_1: null,
          submission_attachment_2: null,
          submission_attachment_3: null,
          submission_image_link_1: null,
          submission_image_link_2: null,
          submission_image_link_3: null,
          category: {
            id: 1,
            category: 'Education',
          },
          challenge: {
            id: 2,
            name: 'Front-end Side Project',
            point_value: 75,
            description: 'Develop a side project using curriculum technology.',
            requirements_1: 'Use HTML, CSS, JS, React, or Angular',
            requirements_2: 'Use an outside API.',
            requirements_3: 'Must be approved by an instructor.',
            requirements_4: 'Must provide link to Repo.',
            requirements_5: null,
          },
          student: {
            id: 1,
            username: 'algorythmist',
            name: 'Thomas Stang',
          },
        },
        {
          id: 19,
          student_id: 2,
          challenge_id: 2,
          cohort_id: 1,
          category_id: 1,
          submission_message: 'Built a front-end app for g42beats api',
          evaluation_message: null,
          submission_status: 'Pending approval',
          submission_attachment_1: null,
          submission_attachment_2: null,
          submission_attachment_3: null,
          submission_image_link_1: null,
          submission_image_link_2: null,
          submission_image_link_3: null,
          category: {
            id: 1,
            category: 'Education',
          },
          challenge: {
            id: 2,
            name: 'Front-end Side Project',
            point_value: 75,
            description: 'Develop a side project using curriculum technology.',
            requirements_1: 'Use HTML, CSS, JS, React, or Angular',
            requirements_2: 'Use an outside API.',
            requirements_3: 'Must be approved by an instructor.',
            requirements_4: 'Must provide link to Repo.',
            requirements_5: null,
          },
          student: {
            id: 2,
            username: 'leveluppal',
            name: 'Sanjeet Uppal',
          },
        },
        {
          id: 20,
          student_id: 3,
          challenge_id: 5,
          cohort_id: 1,
          category_id: 3,
          submission_message: 'Published article required for career services',
          evaluation_message: null,
          submission_status: 'Approved',
          submission_attachment_1: 'https://medium.com/@danielgardner/how-to-overcome-the-fear-of-changing-careers-8d5081225f34',
          submission_attachment_2: null,
          submission_attachment_3: null,
          submission_image_link_1: null,
          submission_image_link_2: null,
          submission_image_link_3: null,
          category: {
            id: 3,
            category: 'Career',
          },
          challenge: {
            id: 5,
            name: 'Write your heart out',
            point_value: 50,
            description: 'Publish an original article with a minimum 750 word length. Must be an additional article to the minimum requirement.',
            requirements_1: 'Article published to Medium or LinkedIn.',
            requirements_2: null,
            requirements_3: null,
            requirements_4: null,
            requirements_5: null,
          },
          student: {
            id: 3,
            username: 'dan_m_g',
            name: 'Daniel Gardner',
          },
        },
        {
          id: 21,
          student_id: 1,
          challenge_id: 5,
          cohort_id: 1,
          category_id: 3,
          submission_message: 'Published article required for career services',
          evaluation_message: null,
          submission_status: 'Approved',
          submission_attachment_1: null,
          submission_attachment_2: null,
          submission_attachment_3: null,
          submission_image_link_1: null,
          submission_image_link_2: null,
          submission_image_link_3: null,
          category: {
            id: 3,
            category: 'Career',
          },
          challenge: {
            id: 5,
            name: 'Write your heart out',
            point_value: 50,
            description: 'Publish an original article with a minimum 750 word length. Must be an additional article to the minimum requirement.',
            requirements_1: 'Article published to Medium or LinkedIn.',
            requirements_2: null,
            requirements_3: null,
            requirements_4: null,
            requirements_5: null,
          },
          student: {
            id: 1,
            username: 'algorythmist',
            name: 'Thomas Stang',
          },
        },
        {
          id: 22,
          student_id: 2,
          challenge_id: 5,
          cohort_id: 1,
          category_id: 3,
          submission_message: 'Published article required for career services',
          evaluation_message: null,
          submission_status: 'Approved',
          submission_attachment_1: null,
          submission_attachment_2: null,
          submission_attachment_3: null,
          submission_image_link_1: null,
          submission_image_link_2: null,
          submission_image_link_3: null,
          category: {
            id: 3,
            category: 'Career',
          },
          challenge: {
            id: 5,
            name: 'Write your heart out',
            point_value: 50,
            description: 'Publish an original article with a minimum 750 word length. Must be an additional article to the minimum requirement.',
            requirements_1: 'Article published to Medium or LinkedIn.',
            requirements_2: null,
            requirements_3: null,
            requirements_4: null,
            requirements_5: null,
          },
          student: {
            id: 2,
            username: 'leveluppal',
            name: 'Sanjeet Uppal',
          },
        },
        {
          id: 23,
          student_id: 1,
          challenge_id: 4,
          cohort_id: 1,
          category_id: 1,
          submission_message: 'Built a gamefication app for galvanize students to maxmize their experience',
          evaluation_message: null,
          submission_status: 'Approved',
          submission_attachment_1: null,
          submission_attachment_2: null,
          submission_attachment_3: null,
          submission_image_link_1: null,
          submission_image_link_2: null,
          submission_image_link_3: null,
          category: {
            id: 1,
            category: 'Education',
          },
          challenge: {
            id: 4,
            name: 'Full-stack Side Project',
            point_value: 200,
            description: 'Develop a side project using curriculum technology.',
            requirements_1: 'Use HTML, CSS, JS, React, or Angular',
            requirements_2: 'Build a backend server using Node, Express, Postgres, and Knex.',
            requirements_3: 'Use an outside API or make your own.',
            requirements_4: 'Must be approved by an instructor.',
            requirements_5: 'Must provide link to Repo.',
          },
          student: {
            id: 1,
            username: 'algorythmist',
            name: 'Thomas Stang',
          },
        },
        {
          id: 24,
          student_id: 2,
          challenge_id: 4,
          cohort_id: 1,
          category_id: 1,
          submission_message: 'Built a gamefication app for galvanize students to maxmize their experience',
          evaluation_message: null,
          submission_status: 'Approved',
          submission_attachment_1: null,
          submission_attachment_2: null,
          submission_attachment_3: null,
          submission_image_link_1: null,
          submission_image_link_2: null,
          submission_image_link_3: null,
          category: {
            id: 1,
            category: 'Education',
          },
          challenge: {
            id: 4,
            name: 'Full-stack Side Project',
            point_value: 200,
            description: 'Develop a side project using curriculum technology.',
            requirements_1: 'Use HTML, CSS, JS, React, or Angular',
            requirements_2: 'Build a backend server using Node, Express, Postgres, and Knex.',
            requirements_3: 'Use an outside API or make your own.',
            requirements_4: 'Must be approved by an instructor.',
            requirements_5: 'Must provide link to Repo.',
          },
          student: {
            id: 2,
            username: 'leveluppal',
            name: 'Sanjeet Uppal',
          },
        },
        {
          id: 25,
          student_id: 3,
          challenge_id: 4,
          cohort_id: 1,
          category_id: 1,
          submission_message: 'Built a gamefication app for galvanize students to maxmize their experience',
          evaluation_message: null,
          submission_status: 'Approved',
          submission_attachment_1: null,
          submission_attachment_2: null,
          submission_attachment_3: null,
          submission_image_link_1: null,
          submission_image_link_2: null,
          submission_image_link_3: null,
          category: {
            id: 1,
            category: 'Education',
          },
          challenge: {
            id: 4,
            name: 'Full-stack Side Project',
            point_value: 200,
            description: 'Develop a side project using curriculum technology.',
            requirements_1: 'Use HTML, CSS, JS, React, or Angular',
            requirements_2: 'Build a backend server using Node, Express, Postgres, and Knex.',
            requirements_3: 'Use an outside API or make your own.',
            requirements_4: 'Must be approved by an instructor.',
            requirements_5: 'Must provide link to Repo.',
          },
          student: {
            id: 3,
            username: 'dan_m_g',
            name: 'Daniel Gardner',
          },
        },
        {
          id: 26,
          student_id: 1,
          challenge_id: 1,
          cohort_id: 1,
          category_id: 2,
          submission_message: 'Held one hour of office hours on May 5th',
          evaluation_message: null,
          submission_status: 'Pending approval',
          submission_attachment_1: null,
          submission_attachment_2: null,
          submission_attachment_3: null,
          submission_image_link_1: null,
          submission_image_link_2: null,
          submission_image_link_3: null,
          category: {
            id: 2,
            category: 'Community',
          },
          challenge: {
            id: 1,
            name: 'Hold TA Hours',
            point_value: 15,
            description: 'Hold TA hours for a junior cohort for at least an hour.',
            requirements_1: 'Hold hours between 5pm and 6pm or during lab time.',
            requirements_2: null,
            requirements_3: null,
            requirements_4: null,
            requirements_5: null,
          },
          student: {
            id: 1,
            username: 'algorythmist',
            name: 'Thomas Stang',
          },
        },
        {
          id: 27,
          student_id: 3,
          challenge_id: 1,
          cohort_id: 1,
          category_id: 2,
          submission_message: 'Held one hour of office hours on May 7th',
          evaluation_message: null,
          submission_status: 'Pending approval',
          submission_attachment_1: null,
          submission_attachment_2: null,
          submission_attachment_3: null,
          submission_image_link_1: null,
          submission_image_link_2: null,
          submission_image_link_3: null,
          category: {
            id: 2,
            category: 'Community',
          },
          challenge: {
            id: 1,
            name: 'Hold TA Hours',
            point_value: 15,
            description: 'Hold TA hours for a junior cohort for at least an hour.',
            requirements_1: 'Hold hours between 5pm and 6pm or during lab time.',
            requirements_2: null,
            requirements_3: null,
            requirements_4: null,
            requirements_5: null,
          },
          student: {
            id: 3,
            username: 'dan_m_g',
            name: 'Daniel Gardner',
          },
        },
        {
          id: 28,
          student_id: 4,
          challenge_id: 5,
          cohort_id: 1,
          category_id: 3,
          submission_message: 'Published article on medium',
          evaluation_message: null,
          submission_status: 'Approved',
          submission_attachment_1: 'https://medium.com/',
          submission_attachment_2: null,
          submission_attachment_3: null,
          submission_image_link_1: null,
          submission_image_link_2: null,
          submission_image_link_3: null,
          category: {
            id: 3,
            category: 'Career',
          },
          challenge: {
            id: 5,
            name: 'Write your heart out',
            point_value: 50,
            description: 'Publish an original article with a minimum 750 word length. Must be an additional article to the minimum requirement.',
            requirements_1: 'Article published to Medium or LinkedIn.',
            requirements_2: null,
            requirements_3: null,
            requirements_4: null,
            requirements_5: null,
          },
          student: {
            id: 4,
            username: 'lvl^-Demo',
            name: 'lvl^ - Demo',
          },
        },
        {
          id: 29,
          student_id: 4,
          challenge_id: 5,
          cohort_id: 1,
          category_id: 3,
          submission_message: 'Published article on LinkedIn',
          evaluation_message: null,
          submission_status: 'Pending approval',
          submission_attachment_1: 'http://linkedin.com/home',
          submission_attachment_2: null,
          submission_attachment_3: null,
          submission_image_link_1: null,
          submission_image_link_2: null,
          submission_image_link_3: null,
          category: {
            id: 3,
            category: 'Career',
          },
          challenge: {
            id: 5,
            name: 'Write your heart out',
            point_value: 50,
            description: 'Publish an original article with a minimum 750 word length. Must be an additional article to the minimum requirement.',
            requirements_1: 'Article published to Medium or LinkedIn.',
            requirements_2: null,
            requirements_3: null,
            requirements_4: null,
            requirements_5: null,
          },
          student: {
            id: 4,
            username: 'lvl^-Demo',
            name: 'lvl^ - Demo',
          },
        },
        {
          id: 30,
          student_id: 4,
          challenge_id: 4,
          cohort_id: 1,
          category_id: 1,
          submission_message: 'Built a gamefication app for galvanize students to maxmize their experience',
          evaluation_message: null,
          submission_status: 'Approved',
          submission_attachment_1: 'http://lvlup.tech',
          submission_attachment_2: 'https://github.com/danielmarcgardner/level-up',
          submission_attachment_3: null,
          submission_image_link_1: 'https://ucarecdn.com/78c9bf05-2244-4e3a-936f-71b6a724f94d/',
          submission_image_link_2: null,
          submission_image_link_3: null,
          category: {
            id: 1,
            category: 'Education',
          },
          challenge: {
            id: 4,
            name: 'Full-stack Side Project',
            point_value: 200,
            description: 'Develop a side project using curriculum technology.',
            requirements_1: 'Use HTML, CSS, JS, React, or Angular',
            requirements_2: 'Build a backend server using Node, Express, Postgres, and Knex.',
            requirements_3: 'Use an outside API or make your own.',
            requirements_4: 'Must be approved by an instructor.',
            requirements_5: 'Must provide link to Repo.',
          },
          student: {
            id: 4,
            username: 'lvl^-Demo',
            name: 'lvl^ - Demo',
          },
        },
        {
          id: 31,
          student_id: 4,
          challenge_id: 1,
          cohort_id: 1,
          category_id: 2,
          submission_message: 'Mentored a student in g52',
          evaluation_message: null,
          submission_status: 'Approved',
          submission_attachment_1: null,
          submission_attachment_2: null,
          submission_attachment_3: null,
          submission_image_link_1: null,
          submission_image_link_2: null,
          submission_image_link_3: null,
          category: {
            id: 2,
            category: 'Community',
          },
          challenge: {
            id: 1,
            name: 'Hold TA Hours',
            point_value: 15,
            description: 'Hold TA hours for a junior cohort for at least an hour.',
            requirements_1: 'Hold hours between 5pm and 6pm or during lab time.',
            requirements_2: null,
            requirements_3: null,
            requirements_4: null,
            requirements_5: null,
          },
          student: {
            id: 4,
            username: 'lvl^-Demo',
            name: 'lvl^ - Demo',
          },
        },
        {
          id: 32,
          student_id: 4,
          challenge_id: 7,
          cohort_id: 1,
          category_id: 1,
          submission_message: 'Reviewed Joes Q1 Project code',
          evaluation_message: null,
          submission_status: 'Pending approval',
          submission_attachment_1: 'https://github.com/',
          submission_attachment_2: null,
          submission_attachment_3: null,
          submission_image_link_1: null,
          submission_image_link_2: null,
          submission_image_link_3: null,
          category: {
            id: 1,
            category: 'Education',
          },
          challenge: {
            id: 7,
            name: 'Code Review a Project for a Student in a Lower Cohort ',
            point_value: 25,
            description: 'Review the code and provide helpful suggestions on how they can improve their code.',
            requirements_1: 'Must be approved by an instructor.',
            requirements_2: 'Please link the repo.',
            requirements_3: null,
            requirements_4: null,
            requirements_5: null,
          },
          student: {
            id: 4,
            username: 'lvl^-Demo',
            name: 'lvl^ - Demo',
          },
        },
        {
          id: 33,
          student_id: 4,
          challenge_id: 1,
          cohort_id: 1,
          category_id: 2,
          submission_message: 'Held one hour of office hours on May 5th',
          evaluation_message: null,
          submission_status: 'Denied',
          submission_attachment_1: null,
          submission_attachment_2: null,
          submission_attachment_3: null,
          submission_image_link_1: null,
          submission_image_link_2: null,
          submission_image_link_3: null,
          category: {
            id: 2,
            category: 'Community',
          },
          challenge: {
            id: 1,
            name: 'Hold TA Hours',
            point_value: 15,
            description: 'Hold TA hours for a junior cohort for at least an hour.',
            requirements_1: 'Hold hours between 5pm and 6pm or during lab time.',
            requirements_2: null,
            requirements_3: null,
            requirements_4: null,
            requirements_5: null,
          },
          student: {
            id: 4,
            username: 'lvl^-Demo',
            name: 'lvl^ - Demo',
          },
        },
        {
          id: 34,
          student_id: 4,
          challenge_id: 9,
          cohort_id: 1,
          category_id: 3,
          submission_message: 'Attended the big tech conference at Moscone Center',
          evaluation_message: null,
          submission_status: 'Pending approval',
          submission_attachment_1: null,
          submission_attachment_2: null,
          submission_attachment_3: null,
          submission_image_link_1: 'https://ucarecdn.com/5cc8b267-14f3-4c2f-bbe3-5e511d2be09f/',
          submission_image_link_2: null,
          submission_image_link_3: null,
          category: {
            id: 3,
            category: 'Career',
          },
          challenge: {
            id: 9,
            name: 'Attend a Conference',
            point_value: 30,
            description: 'Attend a developer conference outside of class time.',
            requirements_1: 'Please submit receipt of attendance or a picture.',
            requirements_2: null,
            requirements_3: null,
            requirements_4: null,
            requirements_5: null,
          },
          student: {
            id: 4,
            username: 'lvl^-Demo',
            name: 'lvl^ - Demo',
          },
        },
        {
          id: 35,
          student_id: 4,
          challenge_id: 12,
          cohort_id: 1,
          category_id: 3,
          submission_message: 'Held a Javascript lovers meetup on may 25th',
          evaluation_message: null,
          submission_status: 'Pending approval',
          submission_attachment_1: 'http://www.meetup.com/',
          submission_attachment_2: null,
          submission_attachment_3: null,
          submission_image_link_1: 'https://ucarecdn.com/5cc8b267-14f3-4c2f-bbe3-5e511d2be09f/',
          submission_image_link_2: 'https://ucarecdn.com/58aef73f-f0f2-46ef-8d21-7e808fffe3fd/',
          submission_image_link_3: null,
          category: {
            id: 3,
            category: 'Career',
          },
          challenge: {
            id: 12,
            name: 'Host a Meet-up',
            point_value: 50,
            description: 'Host a one time technology based meetup.',
            requirements_1: 'Show an invitation or or event on meetup with description of meeting.',
            requirements_2: 'Show pictures of event.',
            requirements_3: null,
            requirements_4: null,
            requirements_5: null,
          },
          student: {
            id: 4,
            username: 'lvl^-Demo',
            name: 'lvl^ - Demo',
          },
        },
        {
          id: 36,
          student_id: 4,
          challenge_id: 10,
          cohort_id: 1,
          category_id: 1,
          submission_message: 'Learned bookshelf.js',
          evaluation_message: null,
          submission_status: 'Approved',
          submission_attachment_1: 'https://github.com',
          submission_attachment_2: null,
          submission_attachment_3: null,
          submission_image_link_1: 'https://ucarecdn.com/ec937656-34fc-4905-b999-8a3cb707cedf/',
          submission_image_link_2: null,
          submission_image_link_3: null,
          category: {
            id: 1,
            category: 'Education',
          },
          challenge: {
            id: 10,
            name: 'Learn a New Technology and Implement it',
            point_value: 50,
            description: 'Learn a new technology and complete a small project based on the new technology and receive a 50 point bonus.',
            requirements_1: 'Not taught by Galvanize.',
            requirements_2: 'Must provide link to Repo.',
            requirements_3: 'Must be approved by an instructor.',
            requirements_4: 'Submit either Front End Side Project, Back End Side Project, or Full Stack Side Project.',
            requirements_5: null,
          },
          student: {
            id: 4,
            username: 'lvl^-Demo',
            name: 'lvl^ - Demo',
          },
        },
      ], done);
  });
  it('Should return a 401 if not logged in', (done) => {
    supertest(app)
      .get('/api/submissions/cohorts/1')
      .set('Accept', 'application/json')
      .expect(401, 'Unauthorize', done);
  });
});

describe('POST /submissions', () => {
  it('Should allow a student to make a challenge submission', (done) => {
    const newSubmission = {
      student_id: 1,
      challenge_id: 1,
      cohort_id: 1,
      category_id: 2,
      submission_message: 'Held TA Hours with insert member of g52 here',
      submission_image_link_1: 'http://imagehosting.com',
    };
    supertest(app)
      .post('/api/submissions')
      .set('Accept', 'application/json')
      .set('Cookie', 'authToken=adminToken')
      .send(newSubmission)
      .expect((response) => {
        delete response.body.created_at;
        delete response.body.updated_at;
      })
      .expect(200, {
        id: 37,
        student_id: 1,
        challenge_id: 1,
        cohort_id: 1,
        category_id: 2,
        submission_message: 'Held TA Hours with insert member of g52 here',
        submission_status: 'Pending approval',
        submission_image_link_1: 'http://imagehosting.com',
      }, done);
  });
  it('Should return a 401 if not logged in', (done) => {
    supertest(app)
      .post('/api/submissions')
      .set('Accept', 'application/json')
      .expect(401, 'Unauthorize', done);
  });
});

describe('GET /submissions/students/:student_id', () => {
  it('Should get all challenge submissions by a single student', (done) => {
    supertest(app)
      .get('/api/submissions/students/3')
      .set('Accept', 'application/json')
      .set('Cookie', 'authToken=adminToken')
      .expect((response) => {
        for (let i = 0; i < response.body.length; i++) {
          delete response.body[i].created_at;
          delete response.body[i].updated_at;
        }
      })
      .expect(200, [
        {
          id: 2,
          student_id: 3,
          challenge_id: 4,
          cohort_id: 1,
          category_id: 1,
          submission_message: 'Built an app that allows users to add their jacket size. It also tracks fulfillment status us to whether student has received their gSwag.',
          evaluation_message: null,
          submission_status: 'Approved',
          submission_attachment_1: 'http://ghoodies.herokuapp.com',
          submission_attachment_2: 'https://github.com/danielmarcgardner/gHoodies',
          submission_attachment_3: null,
          submission_image_link_1: 'https://ucarecdn.com/d50ece0e-f5e1-47fd-a492-d8561fe02ebb/',
          submission_image_link_2: null,
          submission_image_link_3: null,
          challenge: {
            id: 4,
            name: 'Full-stack Side Project',
            point_value: 200,
            description: 'Develop a side project using curriculum technology.',
          },
          category: {
            id: 1,
            category: 'Education',
          },
          student: {
            id: 3,
            username: 'dan_m_g',
            name: 'Daniel Gardner',
          },
        },
        {
          id: 5,
          student_id: 3,
          challenge_id: 3,
          cohort_id: 1,
          category_id: 1,
          submission_message: 'Built an api that sends JSON of cheese by name, firmness, and animal type',
          evaluation_message: null,
          submission_status: 'Approved',
          submission_attachment_1: 'http://cheeswhiz.herokuapp.com/api-docs/',
          submission_attachment_2: 'https://github.com/danielmarcgardner/cheeswhiz',
          submission_attachment_3: null,
          submission_image_link_1: 'https://ucarecdn.com/d50ece0e-f5e1-47fd-a492-d8561fe02ebb/',
          submission_image_link_2: null,
          submission_image_link_3: null,
          challenge: {
            id: 3,
            name: 'Back-end Side Project',
            point_value: 75,
            description: 'Develop a side project using curriculum technology.',
          },
          category: {
            id: 1,
            category: 'Education',
          },
          student: {
            id: 3,
            username: 'dan_m_g',
            name: 'Daniel Gardner',
          },
        },
        {
          id: 10,
          student_id: 3,
          challenge_id: 2,
          cohort_id: 1,
          category_id: 1,
          submission_message: 'Built a front-end app using SF Open data API and Google Maps API what days and locations food trucks appear in SF',
          evaluation_message: null,
          submission_status: 'Approved',
          submission_attachment_1: 'http://truckingaround.surge.sh/',
          submission_attachment_2: 'https://github.com/danielmarcgardner/Trucking-Around',
          submission_attachment_3: null,
          submission_image_link_1: 'https://ucarecdn.com/d50ece0e-f5e1-47fd-a492-d8561fe02ebb/',
          submission_image_link_2: null,
          submission_image_link_3: null,
          challenge: {
            id: 2,
            name: 'Front-end Side Project',
            point_value: 75,
            description: 'Develop a side project using curriculum technology.',
          },
          category: {
            id: 1,
            category: 'Education',
          },
          student: {
            id: 3,
            username: 'dan_m_g',
            name: 'Daniel Gardner',
          },
        },
        {
          id: 13,
          student_id: 3,
          challenge_id: 5,
          cohort_id: 1,
          category_id: 3,
          submission_message: 'Published article on making a career change',
          evaluation_message: null,
          submission_status: 'Approved',
          submission_attachment_1: 'https://www.linkedin.com/pulse/how-overcome-fear-changing-careers-daniel-gardner',
          submission_attachment_2: null,
          submission_attachment_3: null,
          submission_image_link_1: null,
          submission_image_link_2: null,
          submission_image_link_3: null,
          challenge: {
            id: 5,
            name: 'Write your heart out',
            point_value: 50,
            description: 'Publish an original article with a minimum 750 word length. Must be an additional article to the minimum requirement.',
          },
          category: {
            id: 3,
            category: 'Career',
          },
          student: {
            id: 3,
            username: 'dan_m_g',
            name: 'Daniel Gardner',
          },
        },
        {
          id: 16,
          student_id: 3,
          challenge_id: 1,
          cohort_id: 1,
          category_id: 2,
          submission_message: 'TA during Javascript intro course  on Jan 25th',
          evaluation_message: null,
          submission_status: 'Denied',
          submission_attachment_1: null,
          submission_attachment_2: null,
          submission_attachment_3: null,
          submission_image_link_1: null,
          submission_image_link_2: null,
          submission_image_link_3: null,
          challenge: {
            id: 1,
            name: 'Hold TA Hours',
            point_value: 15,
            description: 'Hold TA hours for a junior cohort for at least an hour.',
          },
          category: {
            id: 2,
            category: 'Community',
          },
          student: {
            id: 3,
            username: 'dan_m_g',
            name: 'Daniel Gardner',
          },
        },
        {
          id: 17,
          student_id: 3,
          challenge_id: 2,
          cohort_id: 1,
          category_id: 1,
          submission_message: 'Built a front-end app for supSeasonal api',
          evaluation_message: null,
          submission_status: 'Pending approval',
          submission_attachment_1: 'http://react-to-the-season.herokuapp.com/',
          submission_attachment_2: 'https://github.com/danielmarcgardner/supseasonal-react',
          submission_attachment_3: null,
          submission_image_link_1: 'https://ucarecdn.com/d50ece0e-f5e1-47fd-a492-d8561fe02ebb/',
          submission_image_link_2: null,
          submission_image_link_3: null,
          challenge: {
            id: 2,
            name: 'Front-end Side Project',
            point_value: 75,
            description: 'Develop a side project using curriculum technology.',
          },
          category: {
            id: 1,
            category: 'Education',
          },
          student: {
            id: 3,
            username: 'dan_m_g',
            name: 'Daniel Gardner',
          },
        },
        {
          id: 20,
          student_id: 3,
          challenge_id: 5,
          cohort_id: 1,
          category_id: 3,
          submission_message: 'Published article required for career services',
          evaluation_message: null,
          submission_status: 'Approved',
          submission_attachment_1: 'https://medium.com/@danielgardner/how-to-overcome-the-fear-of-changing-careers-8d5081225f34',
          submission_attachment_2: null,
          submission_attachment_3: null,
          submission_image_link_1: null,
          submission_image_link_2: null,
          submission_image_link_3: null,
          challenge: {
            id: 5,
            name: 'Write your heart out',
            point_value: 50,
            description: 'Publish an original article with a minimum 750 word length. Must be an additional article to the minimum requirement.',
          },
          category: {
            id: 3,
            category: 'Career',
          },
          student: {
            id: 3,
            username: 'dan_m_g',
            name: 'Daniel Gardner',
          },
        },
        {
          id: 25,
          student_id: 3,
          challenge_id: 4,
          cohort_id: 1,
          category_id: 1,
          submission_message: 'Built a gamefication app for galvanize students to maxmize their experience',
          evaluation_message: null,
          submission_status: 'Approved',
          submission_attachment_1: null,
          submission_attachment_2: null,
          submission_attachment_3: null,
          submission_image_link_1: null,
          submission_image_link_2: null,
          submission_image_link_3: null,
          challenge: {
            id: 4,
            name: 'Full-stack Side Project',
            point_value: 200,
            description: 'Develop a side project using curriculum technology.',
          },
          category: {
            id: 1,
            category: 'Education',
          },
          student: {
            id: 3,
            username: 'dan_m_g',
            name: 'Daniel Gardner',
          },
        },
        {
          id: 27,
          student_id: 3,
          challenge_id: 1,
          cohort_id: 1,
          category_id: 2,
          submission_message: 'Held one hour of office hours on May 7th',
          evaluation_message: null,
          submission_status: 'Pending approval',
          submission_attachment_1: null,
          submission_attachment_2: null,
          submission_attachment_3: null,
          submission_image_link_1: null,
          submission_image_link_2: null,
          submission_image_link_3: null,
          challenge: {
            id: 1,
            name: 'Hold TA Hours',
            point_value: 15,
            description: 'Hold TA hours for a junior cohort for at least an hour.',
          },
          category: {
            id: 2,
            category: 'Community',
          },
          student: {
            id: 3,
            username: 'dan_m_g',
            name: 'Daniel Gardner',
          },
        },
      ], done);
  });
  it('Should return a 401 if not logged in', (done) => {
    supertest(app)
      .get('/api/submissions/1')
      .set('Accept', 'application/json')
      .expect(401, 'Unauthorize', done);
  });
});

describe('GET /submissions/:submission_id', () => {
  it('Should pull up a single challenge submission based on id', (done) => {
    supertest(app)
      .get('/api/submissions/1')
      .set('Accept', 'application/json')
      .set('Cookie', 'authToken=adminToken')
      .expect((response) => {
        delete response.body.updated_at;
        delete response.body.created_at;
      })
      .expect(200, {
        id: 1,
        student_id: 1,
        challenge_id: 4,
        cohort_id: 1,
        category_id: 1,
        submission_message: 'Built an app that allows users to add their jacket size. It also tracks fulfillment status us to whether student has received their gSwag.',
        evaluation_message: null,
        submission_status: 'Approved',
        submission_attachment_1: null,
        submission_attachment_2: null,
        submission_attachment_3: null,
        submission_image_link_1: null,
        submission_image_link_2: null,
        submission_image_link_3: null,
        challenge: {
          id: 4,
          name: 'Full-stack Side Project',
          point_value: 200,
          description: 'Develop a side project using curriculum technology.',
          requirements_1: 'Use HTML, CSS, JS, React, or Angular',
          requirements_2: 'Build a backend server using Node, Express, Postgres, and Knex.',
          requirements_3: 'Use an outside API or make your own.',
          requirements_4: 'Must be approved by an instructor.',
          requirements_5: 'Must provide link to Repo.',
        },
        category: {
          id: 1,
          category: 'Education',
        },
        student: {
          id: 1,
          username: 'algorythmist',
          name: 'Thomas Stang',
        },
      }, done);
  });
  it('Should return a 401 if not logged in', (done) => {
    supertest(app)
      .get('/api/submissions/1')
      .set('Accept', 'application/json')
      .expect(401, 'Unauthorize', done);
  });
});

describe('DELETE /submissions/:submission_id', () => {
  it('Should delete a challenge submission based on id', (done) => {
    supertest(app)
      .delete('/api/submissions/1')
      .set('Accept', 'application/json')
      .set('Cookie', 'authToken=adminToken')
      .expect(200, { message: 'Submission successfully deleted' }, done);
  });
  it('Should return a 401 if not logged in', (done) => {
    supertest(app)
      .delete('/api/submissions/1')
      .set('Accept', 'application/json')
      .expect(401, 'Unauthorize', done);
  });
});

describe('PUT /submissions/:submission_id', () => {
  it('Should allow a student to update a challenge submission message and/or attachments', (done) => {
    const updatedSubmission = {
      submission_message: 'Updated Message with more Attachments!!!',
      submission_attachment_1: 'new attachment 1',
      submission_attachment_2: 'new attachment 2',
      submission_image_link_1: 'http://www.attachment1.com/attachment1',
    };
    supertest(app)
      .put('/api/submissions/1')
      .set('Accept', 'application/json')
      .set('Cookie', 'authToken=adminToken')
      .send(updatedSubmission)
      .expect((response) => {
        delete response.body.updated_at;
        delete response.body.created_at;
      })
      .expect(200, {
        id: 1,
        student_id: 1,
        challenge_id: 4,
        cohort_id: 1,
        category_id: 1,
        submission_message: 'Updated Message with more Attachments!!!',
        evaluation_message: null,
        submission_status: 'Approved',
        submission_attachment_1: 'new attachment 1',
        submission_attachment_2: 'new attachment 2',
        submission_attachment_3: null,
        submission_image_link_1: 'http://www.attachment1.com/attachment1',
        submission_image_link_2: null,
        submission_image_link_3: null,
      }, done);
  });
  it('Should return a 401 if not logged in', (done) => {
    supertest(app)
      .put('/api/submissions/1')
      .set('Accept', 'application/json')
      .expect(401, 'Unauthorize', done);
  });
});

describe('PUT /submissions/:submission_id/admin', () => {
  it('Should allow an admin to approve a challenge', (done) => {
    const adminUpdate = {
      evaluation_message: 'Great job SJ!',
      submission_status: 'Approved',
    };
    supertest(app)
      .put('/api/submissions/3/admin')
      .set('Accept', 'application/json')
      .set('Cookie', 'authToken=adminToken')
      .send(adminUpdate)
      .expect((response) => {
        delete response.body.updated_at;
        delete response.body.created_at;
      })
      .expect(200,
      {
        id: 3,
        student_id: 2,
        challenge_id: 1,
        cohort_id: 1,
        category_id: 2,
        submission_message: 'Held one hour of office hours on May 6th',
        evaluation_message: 'Great job SJ!',
        submission_status: 'Approved',
        submission_attachment_1: null,
        submission_attachment_2: null,
        submission_attachment_3: null,
        submission_image_link_1: null,
        submission_image_link_2: null,
        submission_image_link_3: null,
      }, done);
  });
  it('Should return a 401 if not logged in', (done) => {
    supertest(app)
      .put('/api/submissions/1/admin')
      .set('Accept', 'application/json')
      .expect(401, 'Unauthorize', done);
  });
});
