exports.seed = function (knex, Promise) {
  return knex('rewards').del()
  .then(() => knex('rewards').insert([
    {
      id: 1,
      name: 'Gift Card to Gather',
      point_cost: 25,
      description: '$5 gift card to the Gather cafe. Limit one per student.',
      campus_id: 1,
      category_id: 4,
      active: 'Active',
    },
    {
      id: 2,
      name: 'Gift Card to Gather',
      point_cost: 50,
      description: '$10 gift card to the Gather cafe. Limit one per student.',
      campus_id: 1,
      category_id: 4,
      active: 'Active',
    },
    {
      id: 3,
      name: 'Gift Card to Gather',
      point_cost: 100,
      description: '$20 gift card to the Gather cafe. Limit one per student.',
      campus_id: 1,
      category_id: 4,
      active: 'Active',
    },
    {
      id: 4,
      name: 'Gift Card to Gather',
      point_cost: 250,
      description: '$50 gift card to the Gather cafe. Limit one per student.',
      campus_id: 1,
      category_id: 4,
      active: 'Active',
    },
    {
      id: 5,
      name: 'Gift Card to Gather',
      point_cost: 500,
      description: '$100 gift card to the Gather cafe. Limit one per student.',
      campus_id: 1,
      category_id: 4,
      active: 'Active',
    },
    {
      id: 6,
      name: 'The "No You Google!" Card',
      point_cost: 15,
      description: 'The "No You Google!" Card allows a student veto an instructor "google it" response to a question, forcing the instructor to either answer the question or if necessary Google it themselves and report back with the answer.',
      campus_id: 9,
      category_id: 1,
      active: 'Active',
    },
    {
      id: 7,
      name: 'Guaranteed Admission to Community Meet & Eat',
      point_cost: 20,
      description: 'This reward allows a student to secure a guaranteed admission to the next available Community Meet & Eat.',
      campus_id: 9,
      category_id: 2,
      active: 'Active',
    },
    {
      id: 8,
      name: 'Now You Are Official',
      point_cost: 250,
      description: 'A box of professionally designed personal business cards to aid you in your networking and career search.',
      campus_id: 9,
      category_id: 3,
      active: 'Active',
    },
    {
      id: 9,
      name: 'Mock Interview with a Member Company',
      point_cost: 750,
      description: 'Have a mock interview with feedback from a member company.',
      campus_id: 1,
      category_id: 3,
      active: 'Active',
    },
    {
      id: 10,
      name: 'Coaching Lunch',
      point_cost: 500,
      description: 'Have lunch and receive tips on your career search with a member of the Career Services Team, Student Success Manager, or a Member Company.',
      campus_id: 1,
      category_id: 3,
      active: 'Active',
    },
    {
      id: 11,
      name: 'Instructor Pair Programming',
      point_cost: 300,
      description: 'Pair program with the instructor of your choice for 30 minutes.',
      campus_id: 1,
      category_id: 3,
      active: 'Active',
    },
    {
      id: 12,
      name: 'Private Lesson',
      point_cost: 300,
      description: '30 minute 1:1 lesson led by an instructor on technology outside of curriculum. Pick an instructor with a specialty or skill that is not taught by Galvanize (like Swift).',
      campus_id: 1,
      category_id: 1,
      active: 'Active',
    },
    {
      id: 13,
      name: 'Gift Card to Gather',
      point_cost: 1000,
      description: '$200 gift card to the Gather cafe. Limit one per student.',
      campus_id: 1,
      category_id: 4,
      active: 'Active',
    },
    {
      id: 14,
      name: 'Sensei',
      point_cost: 600,
      description: '15 minutes mentor session with a member company.',
      campus_id: 1,
      category_id: 3,
      active: 'Active',
    },
    {
      id: 15,
      name: 'Informational Interview with a Personal Contact',
      point_cost: 1000,
      description: 'Informational Interview set up with a contact by a staff member.',
      campus_id: 1,
      category_id: 3,
      active: 'Active',
    },
    {
      id: 16,
      name: 'Who Said There Is No Such Thing As A Free Lunch?',
      point_cost: 75,
      description: 'Free individual lunch of a $15 value.',
      campus_id: 1,
      category_id: 4,
      active: 'Active',
    },
    {
      id: 17,
      name: 'Pizza Party!!!',
      point_cost: 75,
      description: 'Pizza for all or those that are invited. 75 points per person.',
      campus_id: 1,
      category_id: 4,
      active: 'Active',
    },
    {
      id: 18,
      name: 'Sticker',
      point_cost: 5,
      description: 'Receive a sticker.',
      campus_id: 1,
      category_id: 4,
      active: 'Active',
    },
    {
      id: 19,
      name: 'Code Review',
      point_cost: 300,
      description: '30 minute code review with instructor of choice.',
      campus_id: 1,
      category_id: 1,
      active: 'Active',
    },
    {
      id: 20,
      name: 'Lecture on Outside Curriculum',
      point_cost: 1000,
      description: 'Custom 2 hour lecture on technology outside of Galvanize curriculum.',
      campus_id: 1,
      category_id: 1,
      active: 'Active',
    },
    {
      id: 21,
      name: 'Whiteboarding',
      point_cost: 50,
      description: '15 minute whiteboarding session with instructor of choice.',
      campus_id: 1,
      category_id: 1,
      active: 'Active',
    },
  ]))
  .then(() => knex.raw('SELECT setval(\'rewards_id_seq\', (SELECT MAX(id) FROM rewards))'));
};
